api: 22
saas: 5
ai: 20
automation: 10
containers: 5
observability: 2
integrations: 8
virtualization: 0
data: 39
databases: 4
platform: 1
operations: 16
eventDriven: 1
alignment: 0
openSource: 0
standardization: 4
patterns: 1
specifications: 1
governance: 6
security: 26
code: 0
apache: 0
cncf: 0
cloud: 31
total: 200
