api: 19
saas: 7
ai: 11
automation: 35
containers: 3
observability: 4
integrations: 16
virtualization: 4
data: 76
databases: 10
platform: 12
operations: 11
eventDriven: 3
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 0
governance: 21
security: 36
code: 0
apache: 0
cncf: 0
cloud: 50
total: 323
