api: 6
saas: 0
ai: 2
automation: 8
containers: 2
observability: 2
integrations: 5
virtualization: 1
data: 6
databases: 2
platform: 3
operations: 1
eventDriven: 1
alignment: 0
openSource: 0
standardization: 3
patterns: 2
specifications: 0
governance: 4
security: 9
code: 0
apache: 0
cncf: 0
cloud: 16
total: 73
