api: 35
saas: 14
ai: 58
automation: 46
containers: 9
observability: 4
integrations: 14
virtualization: 3
data: 138
databases: 19
platform: 12
operations: 33
eventDriven: 2
alignment: 1
openSource: 4
standardization: 14
patterns: 3
specifications: 6
governance: 50
security: 37
code: 0
apache: 0
cncf: 0
cloud: 85
total: 580
