api: 38
saas: 0
ai: 25
automation: 53
containers: 4
observability: 4
integrations: 23
virtualization: 6
data: 121
databases: 15
platform: 15
operations: 23
eventDriven: 3
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 4
governance: 42
security: 52
code: 0
apache: 0
cncf: 0
cloud: 96
total: 536
