api: 20
saas: 0
ai: 8
automation: 34
containers: 3
observability: 4
integrations: 16
virtualization: 4
data: 76
databases: 10
platform: 11
operations: 6
eventDriven: 2
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 0
governance: 19
security: 29
code: 0
apache: 0
cncf: 0
cloud: 58
total: 312
