api: 40
saas: 13
ai: 112
automation: 54
containers: 8
observability: 4
integrations: 18
virtualization: 3
data: 165
databases: 11
platform: 16
operations: 26
eventDriven: 5
alignment: 0
openSource: 14
standardization: 10
patterns: 3
specifications: 5
governance: 40
security: 45
code: 1
apache: 0
cncf: 0
cloud: 121
total: 714
