api: 17
saas: 0
ai: 15
automation: 40
containers: 3
observability: 4
integrations: 23
virtualization: 5
data: 84
databases: 11
platform: 11
operations: 11
eventDriven: 2
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 0
governance: 22
security: 23
code: 0
apache: 0
cncf: 0
cloud: 54
total: 337
