api: 12
saas: 8
ai: 43
automation: 19
containers: 0
observability: 2
integrations: 8
virtualization: 0
data: 23
databases: 4
platform: 4
operations: 6
eventDriven: 1
alignment: 0
openSource: 0
standardization: 4
patterns: 1
specifications: 2
governance: 12
security: 12
code: 0
apache: 0
cncf: 0
cloud: 18
total: 179
