api: 36
saas: 5
ai: 32
automation: 27
containers: 4
observability: 3
integrations: 18
virtualization: 5
data: 87
databases: 9
platform: 17
operations: 14
eventDriven: 6
alignment: 1
openSource: 1
standardization: 10
patterns: 4
specifications: 2
governance: 16
security: 22
code: 0
apache: 0
cncf: 0
cloud: 104
total: 423
