api: 15
saas: 3
ai: 23
automation: 37
containers: 7
observability: 4
integrations: 8
virtualization: 4
data: 53
databases: 6
platform: 14
operations: 10
eventDriven: 1
alignment: 0
openSource: 0
standardization: 6
patterns: 3
specifications: 1
governance: 8
security: 11
code: 0
apache: 0
cncf: 0
cloud: 29
total: 243
