api: 0
saas: 0
ai: 2
automation: 5
containers: 0
observability: 0
integrations: 0
virtualization: 0
data: 0
databases: 0
platform: 3
operations: 0
eventDriven: 0
alignment: 0
openSource: 0
standardization: 0
patterns: 1
specifications: 0
governance: 0
security: 0
code: 0
apache: 0
cncf: 0
cloud: 4
total: 15
