api: 25
saas: 8
ai: 98
automation: 34
containers: 3
observability: 4
integrations: 23
virtualization: 3
data: 105
databases: 17
platform: 8
operations: 23
eventDriven: 4
alignment: 0
openSource: 0
standardization: 14
patterns: 3
specifications: 2
governance: 21
security: 43
code: 0
apache: 0
cncf: 0
cloud: 79
total: 514
