api: 21
saas: 9
ai: 7
automation: 23
containers: 4
observability: 3
integrations: 19
virtualization: 3
data: 39
databases: 12
platform: 6
operations: 14
eventDriven: 4
alignment: 0
openSource: 1
standardization: 7
patterns: 4
specifications: 3
governance: 8
security: 25
code: 0
apache: 0
cncf: 0
cloud: 36
total: 241
