api: 24
saas: 22
ai: 37
automation: 27
containers: 3
observability: 4
integrations: 13
virtualization: 3
data: 117
databases: 12
platform: 2
operations: 20
eventDriven: 3
alignment: 0
openSource: 2
standardization: 11
patterns: 3
specifications: 4
governance: 26
security: 13
code: 0
apache: 0
cncf: 0
cloud: 54
total: 382
