api: 14
saas: 0
ai: 8
automation: 32
containers: 2
observability: 3
integrations: 13
virtualization: 4
data: 60
databases: 7
platform: 8
operations: 7
eventDriven: 2
alignment: 0
openSource: 0
standardization: 7
patterns: 3
specifications: 0
governance: 16
security: 21
code: 0
apache: 0
cncf: 0
cloud: 42
total: 249
