api: 34
saas: 23
ai: 42
automation: 74
containers: 6
observability: 6
integrations: 29
virtualization: 10
data: 179
databases: 20
platform: 18
operations: 38
eventDriven: 5
alignment: 0
openSource: 0
standardization: 12
patterns: 6
specifications: 4
governance: 42
security: 52
code: 0
apache: 0
cncf: 0
cloud: 128
total: 705
