api: 47
saas: 21
ai: 37
automation: 74
containers: 4
observability: 4
integrations: 21
virtualization: 7
data: 157
databases: 25
platform: 12
operations: 53
eventDriven: 2
alignment: 1
openSource: 0
standardization: 32
patterns: 3
specifications: 9
governance: 187
security: 82
code: 0
apache: 0
cncf: 0
cloud: 72
total: 835
