api: 21
saas: 12
ai: 15
automation: 51
containers: 4
observability: 4
integrations: 19
virtualization: 5
data: 103
databases: 12
platform: 12
operations: 14
eventDriven: 2
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 2
governance: 20
security: 48
code: 0
apache: 0
cncf: 0
cloud: 82
total: 426
