api: 9
saas: 0
ai: 8
automation: 18
containers: 4
observability: 2
integrations: 7
virtualization: 2
data: 29
databases: 6
platform: 2
operations: 9
eventDriven: 0
alignment: 0
openSource: 0
standardization: 4
patterns: 3
specifications: 1
governance: 6
security: 11
code: 0
apache: 0
cncf: 0
cloud: 20
total: 141
