api: 19
saas: 6
ai: 4
automation: 24
containers: 1
observability: 1
integrations: 10
virtualization: 4
data: 24
databases: 7
platform: 2
operations: 13
eventDriven: 2
alignment: 0
openSource: 0
standardization: 9
patterns: 3
specifications: 4
governance: 12
security: 12
code: 0
apache: 0
cncf: 0
cloud: 42
total: 199
