api: 16
saas: 0
ai: 8
automation: 30
containers: 3
observability: 4
integrations: 15
virtualization: 4
data: 56
databases: 9
platform: 9
operations: 11
eventDriven: 1
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 1
governance: 12
security: 23
code: 0
apache: 0
cncf: 0
cloud: 54
total: 268
