api: 16
saas: 0
ai: 8
automation: 32
containers: 4
observability: 3
integrations: 14
virtualization: 4
data: 66
databases: 9
platform: 10
operations: 6
eventDriven: 1
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 0
governance: 20
security: 28
code: 0
apache: 0
cncf: 0
cloud: 44
total: 277
