api: 18
saas: 12
ai: 14
automation: 36
containers: 4
observability: 4
integrations: 17
virtualization: 6
data: 81
databases: 12
platform: 10
operations: 6
eventDriven: 1
alignment: 0
openSource: 0
standardization: 12
patterns: 4
specifications: 0
governance: 18
security: 26
code: 0
apache: 0
cncf: 0
cloud: 52
total: 321
