api: 26
saas: 3
ai: 6
automation: 17
containers: 2
observability: 1
integrations: 10
virtualization: 3
data: 70
databases: 7
platform: 3
operations: 9
eventDriven: 2
alignment: 0
openSource: 0
standardization: 4
patterns: 3
specifications: 1
governance: 15
security: 18
code: 0
apache: 0
cncf: 0
cloud: 74
total: 274
