api: 10
saas: 12
ai: 10
automation: 14
containers: 0
observability: 1
integrations: 4
virtualization: 0
data: 21
databases: 4
platform: 3
operations: 4
eventDriven: 2
alignment: 0
openSource: 0
standardization: 3
patterns: 3
specifications: 0
governance: 2
security: 3
code: 0
apache: 0
cncf: 0
cloud: 8
total: 94
