api: 21
saas: 0
ai: 12
automation: 40
containers: 3
observability: 4
integrations: 19
virtualization: 5
data: 101
databases: 12
platform: 8
operations: 12
eventDriven: 2
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 0
governance: 28
security: 39
code: 0
apache: 0
cncf: 0
cloud: 76
total: 394
