api: 19
saas: 24
ai: 13
automation: 43
containers: 4
observability: 4
integrations: 21
virtualization: 4
data: 96
databases: 11
platform: 12
operations: 14
eventDriven: 3
alignment: 0
openSource: 0
standardization: 8
patterns: 4
specifications: 2
governance: 22
security: 32
code: 0
apache: 0
cncf: 0
cloud: 74
total: 386
