api: 39
saas: 5
ai: 27
automation: 44
containers: 8
observability: 4
integrations: 22
virtualization: 3
data: 109
databases: 15
platform: 6
operations: 20
eventDriven: 3
alignment: 0
openSource: 0
standardization: 9
patterns: 3
specifications: 2
governance: 36
security: 61
code: 0
apache: 0
cncf: 0
cloud: 94
total: 510
